(function () {
  'use strict';
  if (window.__commonsTeacherSubmission || location.origin !== 'http://localhost:3002' || !/^\/courses\/18(?:\/|$)/.test(location.pathname)) return;
  window.__commonsTeacherSubmission = true;
  const css = 'position:fixed;z-index:2147483647;right:18px;bottom:18px;font:14px Arial,sans-serif;color:#172033';
  const button = document.createElement('button'); button.textContent = 'Teacher Submission'; button.style.cssText = css + ';background:#172033;color:white;border:0;border-radius:999px;padding:10px 15px;box-shadow:0 3px 12px #0004;cursor:pointer';
  const panel = document.createElement('form'); panel.style.cssText = css + ';display:none;width:310px;background:white;border:1px solid #b8c7d9;border-radius:10px;padding:14px;box-shadow:0 3px 18px #0004';
  panel.innerHTML = '<strong>Teacher Submission</strong><label style="display:block;margin-top:10px">Disposition <select name="disposition"><option>KEEP</option><option>CHANGE</option><option>CONFUSING</option><option>BROKEN</option><option>IDEA</option></select></label><label style="display:block;margin-top:8px">What I want / do not want<textarea name="feedback" required rows="5" style="display:block;width:100%;box-sizing:border-box"></textarea></label><label style="display:block;margin-top:8px">What I expected instead<textarea name="expected_outcome" rows="3" style="display:block;width:100%;box-sizing:border-box"></textarea></label><small style="display:block;margin-top:8px;word-break:break-all">Page context is captured from this locked tab.</small><div style="margin-top:10px"><button type="submit">Save receipt</button> <button type="button" data-cancel>Cancel</button></div><output style="display:block;margin-top:8px"></output>';
  document.body.append(button, panel); button.onclick = () => { button.style.display = 'none'; panel.style.display = 'block'; panel.querySelector('textarea').focus(); }; panel.querySelector('[data-cancel]').onclick = () => { panel.reset(); panel.style.display = 'none'; button.style.display = 'block'; };
  panel.onsubmit = async (event) => { event.preventDefault(); const out = panel.querySelector('output'); const f = new FormData(panel); out.textContent = 'Saving…'; try { const response = await fetch('http://127.0.0.1:8765/submit', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({disposition:f.get('disposition'),feedback:f.get('feedback'),expected_outcome:f.get('expected_outcome'),title:document.title,url:location.href})}); const result = await response.json(); if (!response.ok || !result.ok) throw new Error(result.error || 'persistence failed'); out.textContent = 'Saved receipt ' + result.submission_id; panel.reset(); } catch (error) { out.textContent = 'NOT SAVED: ' + error.message; } };
}());
